# run: conda env create --file environment.yml
name: mrsensemakr

channels:
  - anaconda
  - conda-forge

dependencies:
 - python>=3.8
 - pandas
 - numpy
 - statsmodels
 - matplotlib
 - scipy
 - jupyter
 - sphinx-autobuild
 - pip
 - pip:
   - sphinx
